name: Build WordPress Docker Image and push it to docker 

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/logi-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: DockerfileFolder/
        push: true
        tags: tanevh/wordpress_test:latest
